lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
sass:
  sass_dir: vendor/bundle/ruby/3.0.0/gems/bootstrap-5.0.1/assets/stylesheets/
  style: compressed
