name: Compile HTML and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-pages:
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Combile and Deploy HTML
        uses: helaili.jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
